services:
  adk:
    build: .
    command: python3 main.pyc
    environment:
      GOOGLE_GENAI_USE_VERTEXAI: false
      GOOGLE_API_KEY: ${GEMINI_API_KEY}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    ports:
      - 8080:8080
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adk

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4138:4138
      - 4137:4137

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
